### ISSUE TITLE
Considering merge NotebookLM into microcourse 

### ISSUE THREAD

**Issue by SissiFeng** [AccelerationConsortium/ac-microcourses#118]
A couple of ideas about the NotebookLM yesterday:

1. Podcast for AC: make a podcast series for AC scientific paper. This way, we’d expand the reach and make it easier for students and SDL scientists to stay up to date with each other’s research. Instead of reading through everything, they could just listen during their commute or in their free time.
   Here’s an example I tried using the paper other shared in slack:
  https://notebooklm.google.com/notebook/71d889ab-6b87-4277-a8ad-631017f65cbd/audio

2.  Microcourse Summaries as Podcasts: do short podcast summaries at the start of each section or chapter of a microcourse. Some students find the text-heavy format a bit overwhelming, so a quick audio intro could make the material more engaging and helpful.
   I gave it a try with the course1.5 as tutor guidance:
  https://notebooklm.google.com/notebook/38e1c9a3-1000-4af7-9917-ce195005222f/audio

**Comment by sgbaird** [comment]
Really interesting idea. I listened to both, and I think there's potential there. Could you comment on what documents and instructions you provided for each?

Did you end up needing to tune things? Any general impressions about the process or comments on the quality compared to input time spent?

A few specifics I remember (I should have taken notes while listening):

- HT-READ isn't from University of Toronto, and last time I checked, the alloy references weren't quite as close to autonomy as the podcast suggested (in part because automating such high temperatures, solid handling, and complex processing steps can be really challenging)
- Most of the concrete studies weren't too much on the practical side, and the dialogue seemed to suggest the SDL field is further in this application than it actually is. It captured the motivation and context nicely though
- It seemed to miss a fair bit of applications other than "drug discovery and materials science" (i.e., it repeated that a number of times, but I think that may be too narrow and generic). For example, I think there was an optoelectronics section and a reaction optimization section. I think it would benefit from going into more detail about the topics, and I think being shorter and cutting some of the repetition or "fluff"
- the conversational aspect of it makes it pretty easy to listen to. I think it also has a lot of value and friendliness for less technical audiences
- nice that it brought up the 1970's example, and the different types of hardware you might see (e.g., flow chemistry, micro fluidics, mobile robots)
- I think the "questioner/interviewer" voice could benefit from more probing / skeptical questions (while maintaining and overall positive attitude). Likewise, I think the "expert" voice could benefit from toning down the hype with a more balanced view of pros, cons, limitations, and risks, while still maintaining an overall favorable and excited/optimistic tone about the topics.

I think the episodes could be a bit shorter. Or maybe it's ok as-is if some of the "fluff" gets replaced with more technical specifics.

Was the second podcast provided any of the tutorial content, or just the overview page? It might be worth also giving it some of the text from knowledge checks and assignment instructions.

Did you give the first podcast a PDF of the manuscript?

**Comment by SissiFeng** [comment]
The way the first podcast was generated, I modified the prompt a couple times to fine tune it, and most of your comments can be modified in the script. I think this way is meant to be used to give a general background of what's going on. It has the advantage of being a relatively new way of listening. All I fed the model was that paper and some note summaries (where mod focus was required).

For the second assignment tutor, I just send the tutorial to the model. i don't think it's quite enough to be used as a lab guide, at the moment it can be used at most as an introduction to each subsection, or a summary at the end.

Mehrad Ansari  has a thought to incorporate this feature into his pdf summary project.

**Comment by SissiFeng** [comment]
Another try:
https://notebooklm.google.com/notebook/659771fd-9a3f-4b75-a8bd-82087de6a480/audio

This time, I combined more digested notes, but the time control is not work. Still too long.

**Comment by sgbaird** [comment]
(NOTE: above was based on [Miracle_2024_Autonomous R&D of structural materials_COSSMS.pdf](https://github.com/user-attachments/files/17600588/Miracle_2024_Autonomous.R.D.of.structural.materials_COSSMS.pdf)). Agreed that 30 minutes is too long for a 10 page perspective.

> I think this type of podcast is well-suited for thematic introductions rather than focusing on a single paper

That seems to be the case. Let's give it some thought if/how this could be integrated into the courses. @mehradans92, feel free to weigh in. I know there are some other tools more geared towards processing single papers. Open to thoughts.

**Comment by SissiFeng** [comment]
What I can think of for now is that the microcourse could have a subscription-like feature (maybe for registered users or a new service?), releasing a weekly summary podcast. This would cover research highlights from the week (noteworthy papers), condensed into key insights by us, along with some potential connections to SDL. This way, it not only captures current research frontier but also touches on relevant content from certain microcourse sections

**Comment by sgbaird** [comment]
I think this may be outside of the scope of the microcourse, though it's worth keeping in mind. I also want to be really cautious of the volume of AI generated content we release - since the level of careful curation will need to increase with how much we're publicizing or advocating for it.

**Comment by mehradans92** [comment]
Great ideas. Love it. Couple of things, I agree with @sgbaird that we should try to limit the audio time, 5 minute audio containing the top with key points form the paper. Not sure this is a hyperparameter as of now we can change as they have not released an API for NotebookLM. I came across [this]( https://github.com/gabrielchua/open-notebooklm) `gradio` app that might be useful. Overall, I think this is really cool and can be a great addition to micro-courses (as in a quick course summary) and also what we have developed in Spock (not fully done yet but soon to be released). See example on Slack:
![image](https://github.com/user-attachments/assets/1a54729d-ad08-4c5c-8c02-248f7355bfeb)

**Comment by sgbaird** [comment]
Nice find! Looks like https://huggingface.co/spaces/gabrielchua/open-notebooklm lets you choose short (1-2 min) or medium (3-5 min).

It looks like this isn't really tunable and is somewhat random on the NotebookLM side: https://www.reddit.com/r/notebooklm/comments/1fnyv6o/longer_podcasts/.

**Comment by mehradans92** [comment]
Yeah same thing. I read that Reddit too.
So Looks like they just pass it in the input prompt, hoping it would listen lol
https://huggingface.co/spaces/gabrielchua/open-notebooklm/blob/main/app.py#L111

Have you tried this @SissiFeng to see if it actually works?

**Comment by SissiFeng** [comment]
I'm using the gradio above. it hasn't output the audio properly after a few tries. 
And it limits the prompt a lot in the code (maybe for the consideration of fast deployment). 
I’m trying to reference its code.

**Comment by sgbaird** [comment]
> I'm using the gradio above. it hasn't output the audio properly after a few tries. And it limits the prompt a lot in the code (maybe for the consideration of fast deployment). I’m trying to reference its code.

Maybe best to check existing issues in that repo, raise a new one if available, and then wait for a response or update from the devs? Could be a long endeavor, and we're not entirely sure of the quality.

**Comment by sgbaird** [comment]
Per @mehradans92's comment, perhaps we just try to force NotebookLM to give something really short.

**Comment by SissiFeng** [comment]
I checked the code for gradio repo above, and it's a shell for other speech generation packages, not the api for NotebookLM (as far as I know only the meta version of NotebookLlama has an open api interface at the moment)

**Comment by mehradans92** [comment]
> I'm using the gradio above. it hasn't output the audio properly after a few tries. And it limits the prompt a lot in the code (maybe for the consideration of fast deployment). I’m trying to reference its code.

So @SissiFeng what do you mean by "it hasn't output the audio properly"? Like it wouldn't shorten it based on the length you input?
@sgbaird one thing we can do about quality is to maybe use it on a handful of our own papers and then judge the quality.
